/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated.workflows'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthenticatedAdminAgentsRouteImport } from './routes/_authenticated.admin.agents'
import { Route as AuthenticatedAdminAiSearchRouteImport } from './routes/_authenticated.admin.ai-search'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated.admin.integrations'
import { Route as AuthenticatedAdminWorkflowsRouteImport } from './routes/_authenticated.admin.workflows'
import { Route as AuthenticatedSessionIdRouteImport } from './routes/_authenticated.session.$id'
import { Route as AuthenticatedWorkflowsWorkflowIdRouteImport } from './routes/_authenticated.workflows.$workflowId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAgentsRoute =
  AuthenticatedAdminAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiSearchRoute =
  AuthenticatedAdminAiSearchRouteImport.update({
    id: '/ai-search',
    path: '/ai-search',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWorkflowsRoute =
  AuthenticatedAdminWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSessionIdRoute = AuthenticatedSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowsWorkflowIdRoute =
  AuthenticatedWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => AuthenticatedWorkflowsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/ai-search': typeof AuthenticatedAdminAiSearchRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/session/$id': typeof AuthenticatedSessionIdRoute
  '/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/ai-search': typeof AuthenticatedAdminAiSearchRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/session/$id': typeof AuthenticatedSessionIdRoute
  '/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/_authenticated/admin/ai-search': typeof AuthenticatedAdminAiSearchRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/_authenticated/session/$id': typeof AuthenticatedSessionIdRoute
  '/_authenticated/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/settings'
    | '/workflows'
    | '/api/$'
    | '/admin/agents'
    | '/admin/ai-search'
    | '/admin/integrations'
    | '/admin/workflows'
    | '/session/$id'
    | '/workflows/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/admin'
    | '/settings'
    | '/workflows'
    | '/api/$'
    | '/'
    | '/admin/agents'
    | '/admin/ai-search'
    | '/admin/integrations'
    | '/admin/workflows'
    | '/session/$id'
    | '/workflows/$workflowId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/access-denied'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/_authenticated/workflows'
    | '/api/$'
    | '/_authenticated/'
    | '/_authenticated/admin/agents'
    | '/_authenticated/admin/ai-search'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/workflows'
    | '/_authenticated/session/$id'
    | '/_authenticated/workflows/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/agents': {
      id: '/_authenticated/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthenticatedAdminAgentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai-search': {
      id: '/_authenticated/admin/ai-search'
      path: '/ai-search'
      fullPath: '/admin/ai-search'
      preLoaderRoute: typeof AuthenticatedAdminAiSearchRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/workflows': {
      id: '/_authenticated/admin/workflows'
      path: '/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/session/$id': {
      id: '/_authenticated/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof AuthenticatedSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/$workflowId': {
      id: '/_authenticated/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgentsRoute: typeof AuthenticatedAdminAgentsRoute
  AuthenticatedAdminAiSearchRoute: typeof AuthenticatedAdminAiSearchRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminWorkflowsRoute: typeof AuthenticatedAdminWorkflowsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgentsRoute: AuthenticatedAdminAgentsRoute,
  AuthenticatedAdminAiSearchRoute: AuthenticatedAdminAiSearchRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminWorkflowsRoute: AuthenticatedAdminWorkflowsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedWorkflowsRouteChildren {
  AuthenticatedWorkflowsWorkflowIdRoute: typeof AuthenticatedWorkflowsWorkflowIdRoute
}

const AuthenticatedWorkflowsRouteChildren: AuthenticatedWorkflowsRouteChildren =
  {
    AuthenticatedWorkflowsWorkflowIdRoute:
      AuthenticatedWorkflowsWorkflowIdRoute,
  }

const AuthenticatedWorkflowsRouteWithChildren =
  AuthenticatedWorkflowsRoute._addFileChildren(
    AuthenticatedWorkflowsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSessionIdRoute: typeof AuthenticatedSessionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSessionIdRoute: AuthenticatedSessionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
