import { getDefaultSessionCustomMcpServers } from "../session-tools"
import { ALERT_INVESTIGATION_TEMPLATE } from "./alert-investigation-template"
import { WORKFLOW_MANIFEST_VERSION, type WorkflowTemplate } from "./manifest-types"

export const WORKFLOW_TEMPLATES = [
  {
    id: "scratch",
    name: "Start from scratch",
    description: "A minimal manual trigger workflow.",
    complexity: "simple",
    tags: ["manual"],
    manifest: {
      version: WORKFLOW_MANIFEST_VERSION,
      name: "Untitled workflow",
      nodes: [
        {
          id: "manual",
          type: "manual-trigger",
          label: "Manual",
          position: { x: 100, y: 140 },
          options: {},
        },
      ],
      edges: [],
    },
  },
  {
    id: "webhook-isolate",
    name: "Webhook to agent",
    description: "Receive a webhook, normalize the payload, then run an agent.",
    complexity: "simple",
    tags: ["webhook", "agent"],
    manifest: {
      version: WORKFLOW_MANIFEST_VERSION,
      name: "Webhook agent workflow",
      nodes: [
        {
          id: "webhook",
          type: "webhook-trigger",
          label: "Webhook",
          position: { x: 80, y: 140 },
          options: {},
        },
        {
          id: "javascript",
          type: "javascript",
          label: "Normalize payload",
          position: { x: 360, y: 140 },
          options: {
            code: "return inputs.payload ?? null",
          },
        },
        {
          id: "isolate",
          type: "isolate-session",
          label: "Run agent",
          position: { x: 650, y: 140 },
          options: {
            model: "litellm/gpt-5.6-luna",
            reasoningEffort: "",
            prompt: "{{inputs.context}}",
            sessionKey: "",
            cacheKey: "",
            cacheTtlSeconds: "",
            incognito: true,
            subagents: "enabled",
            tools: [],
            customMcpServers: getDefaultSessionCustomMcpServers(),
          },
        },
      ],
      edges: [
        {
          id: "webhook-body-javascript",
          source: "webhook",
          target: "javascript",
          sourceHandle: "body",
          targetHandle: "payload",
        },
        {
          id: "javascript-result-isolate",
          source: "javascript",
          target: "isolate",
          sourceHandle: "result",
          targetHandle: "context",
        },
      ],
    },
  },
  {
    id: "scheduled-http",
    name: "Scheduled request",
    description: "Run on a schedule and call an HTTP endpoint.",
    complexity: "simple",
    tags: ["schedule", "http"],
    manifest: {
      version: WORKFLOW_MANIFEST_VERSION,
      name: "Scheduled request workflow",
      nodes: [
        {
          id: "schedule",
          type: "datetime-trigger",
          label: "Schedule",
          position: { x: 80, y: 140 },
          options: {
            scheduledAt: "",
          },
        },
        {
          id: "request",
          type: "http-request",
          label: "Call endpoint",
          position: { x: 360, y: 140 },
          options: {
            method: "GET",
            url: "",
            headers: {},
            body: "",
            responseType: "auto",
            timeoutMs: 30000,
            failOnHttpError: false,
          },
        },
      ],
      edges: [
        {
          id: "schedule-request",
          source: "schedule",
          target: "request",
          sourceHandle: "firedAt",
          targetHandle: "body",
        },
      ],
    },
  },
  {
    id: "save-output",
    name: "Save workflow output",
    description: "Run JavaScript and save its output to workflow-scoped R2 storage.",
    complexity: "simple",
    tags: ["storage"],
    manifest: {
      version: WORKFLOW_MANIFEST_VERSION,
      name: "Save output workflow",
      nodes: [
        {
          id: "manual",
          type: "manual-trigger",
          label: "Manual",
          position: { x: 80, y: 140 },
          options: {},
        },
        {
          id: "javascript",
          type: "javascript",
          label: "Prepare output",
          position: { x: 340, y: 140 },
          options: {
            code: "return { payload: inputs.payload ?? {}, savedAt: new Date().toISOString() }",
          },
        },
        {
          id: "save",
          type: "r2-put-object",
          label: "Save to R2",
          position: { x: 620, y: 140 },
          options: {
            bucket: "WORKFLOW_BUCKET",
            key: "workflow-outputs/{{workflowId}}/{{runId}}/{{nodeId}}.json",
            contentType: "application/json",
          },
        },
      ],
      edges: [
        {
          id: "manual-javascript",
          source: "manual",
          target: "javascript",
          sourceHandle: "payload",
          targetHandle: "payload",
        },
        {
          id: "javascript-save",
          source: "javascript",
          target: "save",
          sourceHandle: "result",
          targetHandle: "content",
        },
      ],
    },
  },
  {
    id: "slack-qa-bot",
    name: "Slack Q&A bot",
    description: "Answer Slack mentions, DMs, and slash commands from a workflow-hosted Slack app.",
    complexity: "moderate",
    tags: ["slack", "agent", "qa"],
    manifest: {
      version: WORKFLOW_MANIFEST_VERSION,
      name: "Slack Q&A bot",
      nodes: [
        {
          id: "slack_event",
          type: "slack-trigger",
          label: "Slack mention or DM",
          position: { x: 80, y: 100 },
          options: {
            surface: "event",
            eventTypes: ["app_mention", "message"],
            channelNamePattern: "",
            keywordRules: [],
            cooldownSeconds: 0,
            dedupeWindowSeconds: 300,
          },
        },
        {
          id: "slack_command",
          type: "slack-trigger",
          label: "Slash command",
          position: { x: 80, y: 300 },
          options: {
            surface: "command",
            command: "/s0",
            commandDescription: "Ask SolZero",
            cooldownSeconds: 0,
            dedupeWindowSeconds: 300,
          },
        },
        {
          id: "answer",
          type: "isolate-session",
          label: "Answer with SolZero",
          position: { x: 400, y: 200 },
          options: {
            model: "litellm/gpt-5.6-luna",
            reasoningEffort: "",
            prompt:
              "Answer the Slack responder's question. Cite sources when tools return source URLs.\n\nQuestion:\n{{inputs.context}}",
            sessionKey: "",
            cacheKey: "",
            cacheTtlSeconds: "",
            incognito: true,
            subagents: "enabled",
            tools: [],
            customMcpServers: getDefaultSessionCustomMcpServers(),
          },
        },
        {
          id: "reply",
          type: "slack-send-message",
          label: "Reply in Slack",
          position: { x: 720, y: 200 },
          options: {
            channel: "",
            text: "{{inputs.text}}",
            threadTs: "",
            blocks: "",
          },
        },
      ],
      edges: [
        {
          id: "event-text-answer",
          source: "slack_event",
          target: "answer",
          sourceHandle: "text",
          targetHandle: "context",
        },
        {
          id: "command-text-answer",
          source: "slack_command",
          target: "answer",
          sourceHandle: "text",
          targetHandle: "context",
        },
        {
          id: "event-channel-reply",
          source: "slack_event",
          target: "reply",
          sourceHandle: "channelId",
          targetHandle: "channel",
        },
        {
          id: "event-thread-reply",
          source: "slack_event",
          target: "reply",
          sourceHandle: "threadTs",
          targetHandle: "threadTs",
        },
        {
          id: "command-channel-reply",
          source: "slack_command",
          target: "reply",
          sourceHandle: "channelId",
          targetHandle: "channel",
        },
        {
          id: "command-thread-reply",
          source: "slack_command",
          target: "reply",
          sourceHandle: "threadTs",
          targetHandle: "threadTs",
        },
        {
          id: "answer-reply",
          source: "answer",
          target: "reply",
          sourceHandle: "output",
          targetHandle: "text",
        },
      ],
    },
  },
  ALERT_INVESTIGATION_TEMPLATE,
  {
    id: "slack-incident-assistant",
    name: "Slack incident assistant",
    description:
      "Auto-join incident channels, post initial context, answer mentions, and volunteer threaded keyword context.",
    complexity: "complex",
    tags: ["slack", "incident", "sre", "agent"],
    manifest: {
      version: WORKFLOW_MANIFEST_VERSION,
      name: "Slack incident assistant",
      nodes: [
        {
          id: "incident_channel_created",
          type: "slack-trigger",
          label: "Incident channel created",
          position: { x: 28, y: -326 },
          options: {
            surface: "event",
            eventTypes: ["channel_created"],
            channelNamePattern: ".*incident.*",
            keywordRules: [],
            cooldownSeconds: 0,
            dedupeWindowSeconds: 300,
          },
        },
        {
          id: "join_incident_channel",
          type: "slack-join-channel",
          label: "Join incident channel",
          position: { x: 417.7621842473596, y: -321.3890732399275 },
          options: {
            channel: "",
          },
        },
        {
          id: "incident_question",
          type: "slack-trigger",
          label: "Incident mention",
          position: { x: 26, y: 356 },
          options: {
            surface: "event",
            eventTypes: ["app_mention"],
            channelNamePattern: ".*incident.*",
            keywordRules: [],
            cooldownSeconds: 0,
            dedupeWindowSeconds: 300,
          },
        },
        {
          id: "ack_incident_question",
          type: "slack-add-reaction",
          label: "Acknowledge question",
          position: { x: 359.9286558265353, y: 264.6444607041712 },
          options: {
            channel: "",
            timestamp: "",
            name: "s0-thinking",
          },
        },
        {
          id: "fetch_question_thread",
          type: "slack-fetch-thread",
          label: "Fetch question thread",
          position: { x: 368.214032520394, y: 684.6397344181929 },
          options: {
            channel: "",
            threadTs: "",
            limit: 20,
          },
        },
        {
          id: "question_context",
          type: "json-object",
          label: "Question context",
          position: { x: 646.428065040788, y: 578.4209756118205 },
          options: {
            fields: ["question", "thread"],
          },
        },
        {
          id: "answer_incident_question",
          type: "isolate-session",
          label: "Answer incident question",
          position: { x: 904.8584932245652, y: 408.22112194936153 },
          options: {
            model: "litellm/gpt-5.6-luna",
            reasoningEffort: "",
            prompt:
              "You are a read-only incident assistant in a Slack incident channel. Answer with concise, sourced analysis and do not take side-effectful actions. Use configured API-token-backed tools when available.\n\nQuestion and thread context:\n{{inputs.context}}",
            sessionKey: "slack-incident:{{inputs.sessionKey}}",
            cacheKey: "",
            cacheTtlSeconds: "",
            incognito: true,
            subagents: "enabled",
            tools: [],
            customMcpServers: getDefaultSessionCustomMcpServers(),
          },
        },
        {
          id: "reply_to_incident_question",
          type: "slack-send-message",
          label: "Threaded answer",
          position: { x: 1256.9274742550406, y: 427.54815172696567 },
          options: {
            channel: "",
            text: "{{inputs.text}}",
            threadTs: "",
            blocks: "",
          },
        },
        {
          id: "clear_incident_question_ack",
          type: "slack-remove-reaction",
          label: "Clear question acknowledgement",
          position: { x: 1554.9805841578182, y: 256.84714408015367 },
          options: {
            channel: "",
            timestamp: "",
            name: "s0-thinking",
          },
        },
        {
          id: "incident_keyword",
          type: "slack-trigger",
          label: "Incident keyword",
          position: { x: 26.9641995409836, y: 1195.6332606297074 },
          options: {
            surface: "event",
            eventTypes: ["message"],
            channelNamePattern: ".*incident.*",
            keywordRules: ["error", "latency", "deploy", "runbook", "dashboard", "what does"],
            cooldownSeconds: 120,
            dedupeWindowSeconds: 300,
          },
        },
        {
          id: "ack_incident_keyword",
          type: "slack-add-reaction",
          label: "Acknowledge keyword",
          position: { x: 364, y: 1151.2818319793748 },
          options: {
            channel: "",
            timestamp: "",
            name: "s0-thinking",
          },
        },
        {
          id: "proactive_context",
          type: "isolate-session",
          label: "Proactive context",
          position: { x: 379.1967230766332, y: 1562.504182418833 },
          options: {
            model: "litellm/gpt-5.6-luna",
            reasoningEffort: "",
            prompt:
              "A Slack incident message matched a keyword rule. Provide only relevant context if it is likely useful, keep it brief, cite sources, avoid speculation, and do not take side-effectful actions. Use configured API-token-backed tools when available.\n\nMessage:\n{{inputs.context}}",
            sessionKey: "slack-incident:{{inputs.sessionKey}}",
            cacheKey: "",
            cacheTtlSeconds: "",
            incognito: true,
            subagents: "enabled",
            tools: [],
            customMcpServers: getDefaultSessionCustomMcpServers(),
          },
        },
        {
          id: "post_proactive_context",
          type: "slack-send-message",
          label: "Threaded context",
          position: { x: 713.410498852459, y: 1287.8784694744852 },
          options: {
            channel: "",
            text: "{{inputs.text}}",
            threadTs: "",
            blocks: "",
          },
        },
        {
          id: "clear_incident_keyword_ack",
          type: "slack-remove-reaction",
          label: "Clear keyword acknowledgement",
          position: { x: 1018.3382298520677, y: 1118.4986389805483 },
          options: {
            channel: "",
            timestamp: "",
            name: "s0-thinking",
          },
        },
      ],
      edges: [
        {
          id: "created-join",
          source: "incident_channel_created",
          target: "join_incident_channel",
          sourceHandle: "channelId",
          targetHandle: "channel",
        },
        {
          id: "question-ack-channel",
          source: "incident_question",
          target: "ack_incident_question",
          sourceHandle: "channelId",
          targetHandle: "channel",
        },
        {
          id: "question-ack-message",
          source: "incident_question",
          target: "ack_incident_question",
          sourceHandle: "messageTs",
          targetHandle: "timestamp",
        },
        {
          id: "question-fetch-channel",
          source: "incident_question",
          target: "fetch_question_thread",
          sourceHandle: "channelId",
          targetHandle: "channel",
        },
        {
          id: "question-fetch-thread",
          source: "incident_question",
          target: "fetch_question_thread",
          sourceHandle: "threadTs",
          targetHandle: "threadTs",
        },
        {
          id: "question-context-question",
          source: "incident_question",
          target: "question_context",
          sourceHandle: "text",
          targetHandle: "question",
        },
        {
          id: "thread-context-thread",
          source: "fetch_question_thread",
          target: "question_context",
          sourceHandle: "text",
          targetHandle: "thread",
        },
        {
          id: "context-agent",
          source: "question_context",
          target: "answer_incident_question",
          sourceHandle: "object",
          targetHandle: "context",
        },
        {
          id: "question-agent-session-key",
          source: "incident_question",
          target: "answer_incident_question",
          sourceHandle: "channelId",
          targetHandle: "sessionKey",
        },
        {
          id: "question-channel-reply",
          source: "incident_question",
          target: "reply_to_incident_question",
          sourceHandle: "channelId",
          targetHandle: "channel",
        },
        {
          id: "question-thread-reply",
          source: "incident_question",
          target: "reply_to_incident_question",
          sourceHandle: "threadTs",
          targetHandle: "threadTs",
        },
        {
          id: "question-agent-reply",
          source: "answer_incident_question",
          target: "reply_to_incident_question",
          sourceHandle: "output",
          targetHandle: "text",
        },
        {
          id: "question-clear-ack-channel",
          source: "reply_to_incident_question",
          target: "clear_incident_question_ack",
          sourceHandle: "channel",
          targetHandle: "channel",
        },
        {
          id: "question-clear-ack-message",
          source: "incident_question",
          target: "clear_incident_question_ack",
          sourceHandle: "messageTs",
          targetHandle: "timestamp",
        },
        {
          id: "keyword-ack-channel",
          source: "incident_keyword",
          target: "ack_incident_keyword",
          sourceHandle: "channelId",
          targetHandle: "channel",
        },
        {
          id: "keyword-ack-message",
          source: "incident_keyword",
          target: "ack_incident_keyword",
          sourceHandle: "messageTs",
          targetHandle: "timestamp",
        },
        {
          id: "keyword-text-agent",
          source: "incident_keyword",
          target: "proactive_context",
          sourceHandle: "text",
          targetHandle: "context",
        },
        {
          id: "keyword-agent-session-key",
          source: "incident_keyword",
          target: "proactive_context",
          sourceHandle: "channelId",
          targetHandle: "sessionKey",
        },
        {
          id: "keyword-channel-reply",
          source: "incident_keyword",
          target: "post_proactive_context",
          sourceHandle: "channelId",
          targetHandle: "channel",
        },
        {
          id: "keyword-thread-reply",
          source: "incident_keyword",
          target: "post_proactive_context",
          sourceHandle: "threadTs",
          targetHandle: "threadTs",
        },
        {
          id: "keyword-agent-reply",
          source: "proactive_context",
          target: "post_proactive_context",
          sourceHandle: "output",
          targetHandle: "text",
        },
        {
          id: "keyword-clear-ack-channel",
          source: "post_proactive_context",
          target: "clear_incident_keyword_ack",
          sourceHandle: "channel",
          targetHandle: "channel",
        },
        {
          id: "keyword-clear-ack-message",
          source: "incident_keyword",
          target: "clear_incident_keyword_ack",
          sourceHandle: "messageTs",
          targetHandle: "timestamp",
        },
      ],
    },
  },
] as const satisfies readonly WorkflowTemplate[]
