/* oxlint-disable s0-lint/no-if-statement, s0-lint/no-ternary, effect/avoid-direct-json, effect/imperative-loops -- Cloudflare binding compilation is a synchronous deployment boundary; direct guards and size scans keep failures adjacent to the invalid binding. */
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import * as Cloudflare from "alchemy/Cloudflare"
import * as Output from "alchemy/Output"
import { Self } from "alchemy/Self"
import * as Effect from "effect/Effect"
import * as Match from "effect/Match"
import * as Redacted from "effect/Redacted"
import type * as Schema from "effect/Schema"
import {
  MCPCF_PROXY_SIGNING_SECRET_MIN_LENGTH,
  s0RuntimeSecretReferences,
  type CloudflareAiGatewayByokProvider,
  type S0AuthConfig,
  type S0CloudflareAiGatewayConfig,
  type S0LitellmConfig,
  type S0McpcfConfig,
  type S0ResolvedConfig,
  type AdminConfig,
  type SecretReference,
  type StageMetadata,
} from "@solzero/shared"
import type { WorkflowActionsEntrypoint } from "../../../packages/api/src/server/background/workflows/runner"
import type { DeploymentMetadata } from "../../../packages/infra/src/deploymentMetadata"
import type {} from "../env"
import {
  DYNAMIC_WORKFLOW_CLASS_NAME,
  getApiResourceName,
  getDynamicWorkflowName,
  type AgentContainerApplications,
  type AgentContainerNamespaces,
  type AgentResources,
} from "./resources"

export {
  createAgentContainerApplications,
  createAgentContainerNamespaces,
  createAgentResources,
  createDynamicWorkflowResource,
  getApiResourceName,
} from "./resources"
export type {
  AgentContainerApplications,
  AgentContainerNamespaces,
  AgentResources,
} from "./resources"

export type ApiSecretInput = string | Output.Output<Redacted.Redacted<string>>

export interface ApiInfraEnv {
  readonly S0_PROVIDER_LAYER: "live" | "mock"
  readonly S0_CONFIG_FILE: string
  readonly S0_CONFIG_ADMIN: AdminConfig
  readonly S0_CONFIG_AUTH: S0AuthConfig
  readonly S0_CONFIG_CLOUDFLARE_AI_GATEWAY: S0CloudflareAiGatewayConfig
  readonly S0_CONFIG_LITELLM?: S0LitellmConfig
  readonly S0_CONFIG_MCPCF?: S0McpcfConfig
  readonly S0_DEPLOYMENT_CONFIG_DIGEST: string
  readonly configSecretBindings: Readonly<Record<string, ApiSecretInput>>
  readonly cloudflareAiGatewayProviderKeySecrets: Readonly<
    Partial<Record<CloudflareAiGatewayByokProvider, ApiSecretInput>>
  >
  readonly MCPCF_PROXY_SIGNING_SECRET: ApiSecretInput
  readonly TOKEN_ENCRYPTION_KEY: ApiSecretInput
  readonly REPO_SECRETS_ENCRYPTION_KEY: ApiSecretInput
  readonly BETTER_AUTH_SECRET: ApiSecretInput
  readonly GITHUB_APP_CLIENT_ID: string
  readonly GITHUB_APP_CLIENT_SECRET: ApiSecretInput
  readonly GITHUB_APP_ID: string
  readonly GITHUB_APP_PRIVATE_KEY: ApiSecretInput
  readonly GITHUB_APP_SLUG: string
  readonly GITHUB_APP_WEBHOOK_SECRET: ApiSecretInput
  readonly SLACK_TOKEN: ApiSecretInput
  readonly CF_AI_SEARCH_SERVICE_TOKEN_ID: string
}

function secretValue(
  secretBindings: Readonly<Record<string, ApiSecretInput>>,
  reference: SecretReference | null | undefined,
): ApiSecretInput {
  return reference ? (secretBindings[reference.env] ?? "") : ""
}

function configuredStringSecretValue(
  secretBindings: Readonly<Record<string, ApiSecretInput>>,
  reference: SecretReference | null | undefined,
): string {
  const value = secretValue(secretBindings, reference)
  if (typeof value !== "string") {
    throw new Error(`${reference?.env ?? "Secret"} cannot be generated by Alchemy`)
  }
  return value
}

export function getApiInfraEnv(
  config: S0ResolvedConfig,
  configurationFile: string,
  deploymentConfigDigest: string,
  secretBindings: Readonly<Record<string, ApiSecretInput>>,
): ApiInfraEnv {
  const credentialSignInEnabled = Object.values(config.auth.providers).some(
    (provider) =>
      provider.kind === "credential" && provider.enabled && provider.capabilities.signIn,
  )
  if (credentialSignInEnabled && config.admins.adminEmails.length === 0) {
    throw new Error(
      "The active stage config admins.adminEmails must contain at least one address when credential sign-in is enabled",
    )
  }
  if (credentialSignInEnabled) {
    const adminPasswordReference = config.auth.adminPassword
    if (!adminPasswordReference) {
      throw new Error("auth.adminPassword is required when credential sign-in is enabled")
    }
    const adminPassword = secretValue(secretBindings, adminPasswordReference)
    if (typeof adminPassword === "string" && adminPassword.length < 12) {
      throw new Error(`${adminPasswordReference.env} must contain at least 12 characters`)
    }
  }
  const mcpcfProxySigningSecret = secretValue(
    secretBindings,
    config.security.mcpcfProxySigningSecret,
  )
  if (
    typeof mcpcfProxySigningSecret === "string" &&
    mcpcfProxySigningSecret.length < MCPCF_PROXY_SIGNING_SECRET_MIN_LENGTH
  ) {
    throw new Error(
      `${config.security.mcpcfProxySigningSecret.env} must contain at least ${MCPCF_PROXY_SIGNING_SECRET_MIN_LENGTH} characters`,
    )
  }
  const githubApp = config.integrations.githubApp
  const slack = config.integrations.slack
  const configSecretBindings = Object.fromEntries(
    s0RuntimeSecretReferences(config).map((reference) => [
      reference.env,
      secretValue(secretBindings, reference),
    ]),
  )
  const cloudflareAiGatewayProviderKeySecrets = Object.fromEntries(
    Object.entries(config.aiProviders.cloudflareAiGateway.providerKeys ?? {}).map(
      ([providerId, reference]) => [providerId, secretValue(secretBindings, reference)],
    ),
  )
  return {
    S0_PROVIDER_LAYER: "live",
    S0_CONFIG_FILE: configurationFile,
    S0_CONFIG_ADMIN: config.admins,
    S0_CONFIG_AUTH: config.auth,
    S0_CONFIG_CLOUDFLARE_AI_GATEWAY: config.aiProviders.cloudflareAiGateway,
    ...(config.aiProviders.litellm ? { S0_CONFIG_LITELLM: config.aiProviders.litellm } : {}),
    ...(config.mcpcf ? { S0_CONFIG_MCPCF: config.mcpcf } : {}),
    S0_DEPLOYMENT_CONFIG_DIGEST: deploymentConfigDigest,
    configSecretBindings,
    cloudflareAiGatewayProviderKeySecrets,
    MCPCF_PROXY_SIGNING_SECRET: mcpcfProxySigningSecret,
    TOKEN_ENCRYPTION_KEY: secretValue(secretBindings, config.security.tokenEncryptionKey),
    REPO_SECRETS_ENCRYPTION_KEY: secretValue(
      secretBindings,
      config.security.repositorySecretsEncryptionKey,
    ),
    BETTER_AUTH_SECRET: secretValue(secretBindings, config.security.betterAuthSecret),
    GITHUB_APP_CLIENT_ID: githubApp.enabled ? githubApp.clientId : "",
    GITHUB_APP_CLIENT_SECRET: githubApp.enabled
      ? secretValue(secretBindings, githubApp.clientSecret)
      : "",
    GITHUB_APP_ID: githubApp.enabled ? githubApp.appId : "",
    GITHUB_APP_PRIVATE_KEY: githubApp.enabled
      ? secretValue(secretBindings, githubApp.privateKey)
      : "",
    GITHUB_APP_SLUG: githubApp.enabled ? githubApp.slug : "",
    GITHUB_APP_WEBHOOK_SECRET:
      githubApp.enabled && githubApp.webhookSecret
        ? secretValue(secretBindings, githubApp.webhookSecret)
        : "",
    SLACK_TOKEN: slack.enabled ? secretValue(secretBindings, slack.botToken) : "",
    CF_AI_SEARCH_SERVICE_TOKEN_ID: configuredStringSecretValue(
      secretBindings,
      config.aiSearch.serviceTokenId,
    ),
  }
}

export interface CreateApiOptions {
  appName: string
  stageMetadata: StageMetadata
  deploymentMetadata: DeploymentMetadata
  dev: boolean
  cloudflareAccountId: string
  agentResources: AgentResources
  agentContainers: AgentContainerNamespaces
  agentContainerApplications: AgentContainerApplications
  aiGateway?: ApiAiGatewayBinding
  env: ApiInfraEnv
}

export interface ApiAiGatewayBinding {
  readonly resource: Cloudflare.AI.Gateway | Cloudflare.AIBinding
  readonly gatewayId: string | Output.Output<string>
  readonly runToken: ApiSecretInput
  readonly secretsStoreId: string | Output.Output<string>
}

interface CreateApiBindingsOptions {
  appName: string
  dev: boolean
  stageMetadata: StageMetadata
  deploymentMetadata: DeploymentMetadata
  cloudflareAccountId: string
  agentResources: AgentResources
  agentContainers: AgentContainerNamespaces
  aiGateway?: ApiAiGatewayBinding
  env: ApiInfraEnv
  workerName: string
}

function secretInput(
  value: string | Output.Output<Redacted.Redacted<string>>,
): Redacted.Redacted<string> {
  return Match.value(value).pipe(
    Match.when(Match.string, Redacted.make),
    Match.orElse((output) => output),
  ) as Redacted.Redacted<string>
}

function jsonBinding(value: unknown): Schema.Json {
  // Alchemy's JSON binding type requires an index signature, while our decoded
  // configuration DTOs intentionally use exact interfaces. The compiler has
  // already schema-decoded these values before they reach this boundary.
  return value as Schema.Json
}

function workflowActionsBinding(
  service: string,
): Cloudflare.WorkerEntrypointBinding<WorkflowActionsEntrypoint> {
  return {
    BindingType: "Cloudflare.WorkerEntrypointBinding",
    service,
    entrypoint: "WorkflowActions",
  }
}

function dynamicWorkflowBinding(appName: string, stageMetadata: StageMetadata, workerName: string) {
  return Cloudflare.Workflow(getDynamicWorkflowName(appName, stageMetadata.name), {
    className: DYNAMIC_WORKFLOW_CLASS_NAME,
    scriptName: workerName,
  })
}

const MAX_USER_VARIABLE_BINDINGS = 60
const MAX_VARIABLE_BINDING_BYTES = 4_500
const MAX_SECRET_BINDING_BYTES = 5_000

function bindingSize(value: unknown): number {
  const serialized = typeof value === "string" ? value : JSON.stringify(value)
  return new TextEncoder().encode(serialized).byteLength
}

function validateApiVariableBindings(
  variables: Readonly<Record<string, unknown>>,
  secrets: Readonly<Record<string, ApiSecretInput>>,
): void {
  const bindingNames = new Set([...Object.keys(variables), ...Object.keys(secrets)])
  if (bindingNames.size > MAX_USER_VARIABLE_BINDINGS) {
    throw new Error(
      `API Worker configuration defines ${bindingNames.size} variables and secrets; the s0 deployment budget is ${MAX_USER_VARIABLE_BINDINGS} to reserve capacity for Alchemy-managed bindings`,
    )
  }
  for (const [name, value] of Object.entries(variables)) {
    const size = bindingSize(value)
    if (size > MAX_VARIABLE_BINDING_BYTES) {
      throw new Error(
        `API Worker variable ${name} is ${size} bytes; split it before the ${MAX_VARIABLE_BINDING_BYTES}-byte s0 deployment budget`,
      )
    }
  }
  for (const [name, value] of Object.entries(secrets)) {
    if (typeof value !== "string") continue
    const size = bindingSize(value)
    if (size > MAX_SECRET_BINDING_BYTES) {
      throw new Error(
        `API Worker secret ${name} is ${size} bytes; Cloudflare secrets must not exceed ${MAX_SECRET_BINDING_BYTES} bytes`,
      )
    }
  }
}

function createApiBindings(options: CreateApiBindingsOptions) {
  const {
    appName,
    stageMetadata,
    deploymentMetadata,
    cloudflareAccountId,
    agentResources,
    agentContainers,
    aiGateway,
    env,
    workerName,
  } = options

  const variables = {
    STAGE: stageMetadata.name,
    WORKER_NAME: workerName,
    APP_VERSION: deploymentMetadata.appVersion,
    COMMIT_SHA: deploymentMetadata.commitSha,
    S0_PROVIDER_LAYER: env.S0_PROVIDER_LAYER,
    S0_CONFIG_FILE: env.S0_CONFIG_FILE,
    S0_STAGE_METADATA: jsonBinding({
      _tag: stageMetadata._tag,
      name: stageMetadata.name,
      app: stageMetadata.app,
      infra: stageMetadata.infra,
    }),
    S0_CONFIG_ADMIN: jsonBinding(env.S0_CONFIG_ADMIN),
    S0_CONFIG_AUTH: jsonBinding(env.S0_CONFIG_AUTH),
    S0_CONFIG_CLOUDFLARE_AI_GATEWAY: jsonBinding(env.S0_CONFIG_CLOUDFLARE_AI_GATEWAY),
    ...(env.S0_CONFIG_LITELLM ? { S0_CONFIG_LITELLM: jsonBinding(env.S0_CONFIG_LITELLM) } : {}),
    ...(env.S0_CONFIG_MCPCF ? { S0_CONFIG_MCPCF: jsonBinding(env.S0_CONFIG_MCPCF) } : {}),
    S0_DEPLOYMENT_CONFIG_DIGEST: env.S0_DEPLOYMENT_CONFIG_DIGEST,
    CLOUDFLARE_ACCOUNT_ID: cloudflareAccountId,
    GITHUB_APP_CLIENT_ID: env.GITHUB_APP_CLIENT_ID,
    GITHUB_APP_ID: env.GITHUB_APP_ID,
    GITHUB_APP_SLUG: env.GITHUB_APP_SLUG,
    CF_AI_SEARCH_SERVICE_TOKEN_ID: env.CF_AI_SEARCH_SERVICE_TOKEN_ID,
  }
  const fixedSecrets = {
    MCPCF_PROXY_SIGNING_SECRET: env.MCPCF_PROXY_SIGNING_SECRET,
    TOKEN_ENCRYPTION_KEY: env.TOKEN_ENCRYPTION_KEY,
    REPO_SECRETS_ENCRYPTION_KEY: env.REPO_SECRETS_ENCRYPTION_KEY,
    BETTER_AUTH_SECRET: env.BETTER_AUTH_SECRET,
    GITHUB_APP_CLIENT_SECRET: env.GITHUB_APP_CLIENT_SECRET,
    GITHUB_APP_PRIVATE_KEY: env.GITHUB_APP_PRIVATE_KEY,
    GITHUB_APP_WEBHOOK_SECRET: env.GITHUB_APP_WEBHOOK_SECRET,
    SLACK_TOKEN: env.SLACK_TOKEN,
    ...(aiGateway ? { CLOUDFLARE_AI_GATEWAY_RUN_TOKEN: aiGateway.runToken } : {}),
  }
  const secrets = { ...env.configSecretBindings, ...fixedSecrets }
  validateApiVariableBindings(variables, secrets)

  return {
    ...variables,

    ...(aiGateway
      ? {
          AI_GATEWAY: aiGateway.resource,
          AI_GATEWAY_ID: aiGateway.gatewayId,
          AI_GATEWAY_SECRETS_STORE_ID: aiGateway.secretsStoreId,
        }
      : {}),

    // Worker bindings
    WORKFLOW_LOADER: Cloudflare.WorkerLoader(),
    ...(options.dev ? {} : { BROWSER: Cloudflare.Browser() }),
    SESSION: agentResources.sessionNamespace,
    ISOLATE_SESSION: agentResources.isolateSessionNamespace,
    WORKFLOW_ALARM: agentResources.workflowAlarmNamespace,
    DYNAMIC_WORKFLOW: dynamicWorkflowBinding(appName, stageMetadata, workerName),
    ...(agentResources.aiSearchNamespace ? { AI_SEARCH: agentResources.aiSearchNamespace } : {}),
    ...(agentResources.workflowAiSearchNamespace
      ? { WORKFLOW_AI_SEARCH: agentResources.workflowAiSearchNamespace }
      : {}),
    WORKFLOW_ACTIONS: workflowActionsBinding(workerName),
    WORKFLOW_BUCKET: agentResources.workflowBucket,
    AI_SEARCH_CONTENT_BUCKET: agentResources.aiSearchContentBucket,
    DB: agentResources.db,
    S0_CONFIG: agentResources.s0Config,
    REPOS_CACHE: agentResources.repoCache,
    USER_WORKFLOW_KV: agentResources.userWorkflowKv,
    WORKFLOW_SESSION_RESPONSE_CACHE: agentResources.workflowSessionResponseCache,
    OPENCODE_AGENT: agentContainers.opencode,
    CODEX_AGENT: agentContainers.codex,
    CLAUDE_CODE_AGENT: agentContainers.claudeCode,
    AGENT_SKILLS: agentResources.skillsBucket,
    AUTH_SIGN_IN_RATE_LIMIT: Cloudflare.RateLimit("AUTH_SIGN_IN_RATE_LIMIT", {
      namespaceId: 1001,
      simple: { limit: 10, period: 60 },
    }),

    ...Object.fromEntries(
      Object.entries(env.configSecretBindings).map(([name, value]) => [name, secretInput(value)]),
    ),
    MCPCF_PROXY_SIGNING_SECRET: secretInput(fixedSecrets.MCPCF_PROXY_SIGNING_SECRET),
    TOKEN_ENCRYPTION_KEY: secretInput(fixedSecrets.TOKEN_ENCRYPTION_KEY),
    REPO_SECRETS_ENCRYPTION_KEY: secretInput(fixedSecrets.REPO_SECRETS_ENCRYPTION_KEY),
    BETTER_AUTH_SECRET: secretInput(fixedSecrets.BETTER_AUTH_SECRET),
    GITHUB_APP_CLIENT_SECRET: secretInput(fixedSecrets.GITHUB_APP_CLIENT_SECRET),
    GITHUB_APP_PRIVATE_KEY: secretInput(fixedSecrets.GITHUB_APP_PRIVATE_KEY),
    GITHUB_APP_WEBHOOK_SECRET: secretInput(fixedSecrets.GITHUB_APP_WEBHOOK_SECRET),
    SLACK_TOKEN: secretInput(fixedSecrets.SLACK_TOKEN),
    ...(aiGateway
      ? {
          CLOUDFLARE_AI_GATEWAY_RUN_TOKEN: secretInput(aiGateway.runToken),
        }
      : {}),
  }
}

export type ApiWorkerBindingResources = ReturnType<typeof createApiBindings>

export function createApi(options: CreateApiOptions) {
  const {
    appName,
    stageMetadata,
    deploymentMetadata,
    dev,
    cloudflareAccountId,
    agentResources,
    agentContainers,
    agentContainerApplications,
    aiGateway,
    env,
  } = options

  const __filename = fileURLToPath(import.meta.url)
  const __dirname = dirname(__filename)
  const entrypoint = resolve(__dirname, "../index.ts")

  // We replicate Alchemy's naming scheme so we can provide it as a binding env var
  const workerName = `${getApiResourceName(appName)}-${stageMetadata.name}`

  const devConfig = Match.value(dev).pipe(
    Match.when(true, () => ({ dev: { port: 1337 } })),
    Match.orElse(() => ({})),
  )
  const [primaryDomain, ...domainAliases] = stageMetadata.infra.apiDomains
  const domainConfig = Match.value(primaryDomain).pipe(
    Match.when(Match.string, (name) => ({
      domain: {
        name,
        aliases: domainAliases,
      },
      workersDev: false as const,
    })),
    Match.orElse(() => ({})),
  )

  const api = Cloudflare.Worker("api", {
    name: workerName,
    main: entrypoint,
    compatibility: {
      date: "2026-07-21",
      flags: ["nodejs_compat"],
    },
    ...devConfig,
    observability: {
      enabled: true,
      logs: {
        enabled: true,
        destinations: [...stageMetadata.infra.apiObservabilityLogsDestinations],
        invocationLogs: false,
        headSamplingRate: stageMetadata.infra.apiObservabilityLogsHeadSamplingRate,
        persist: true,
      },
      traces: {
        enabled: true,
        destinations: [...stageMetadata.infra.apiObservabilityTracesDestinations],
        headSamplingRate: stageMetadata.infra.apiObservabilityTracesHeadSamplingRate,
        persist: true,
      },
    },
    ...domainConfig,
    crons: ["0 13 * * *", "0 14 * * *"],
    env: createApiBindings({
      appName,
      dev,
      stageMetadata,
      deploymentMetadata,
      cloudflareAccountId,
      agentResources,
      agentContainers,
      aiGateway,
      env,
      workerName,
    }),
  })

  return api.pipe(
    Effect.tap((api) =>
      bindAgentContainerRuntimes({
        api,
        agentContainerApplications,
      }),
    ),
    Effect.tap(() => Effect.log(`API available at ${stageMetadata.infra.serverUrl}`)),
  )
}

function bindAgentContainerRuntimes(options: {
  api: Cloudflare.Worker
  agentContainerApplications: AgentContainerApplications
}) {
  const { api, agentContainerApplications } = options

  return Effect.gen(function* () {
    yield* bindAgentContainerRuntime(api, agentContainerApplications.opencode, {
      logicalId: "opencode-agent",
      className: "OpenCodeAgentContainer",
    })
    yield* bindAgentContainerRuntime(api, agentContainerApplications.codex, {
      logicalId: "codex-agent",
      className: "CodexAgentContainer",
    })
    yield* bindAgentContainerRuntime(api, agentContainerApplications.claudeCode, {
      logicalId: "claude-code-agent",
      className: "ClaudeCodeAgentContainer",
    })
  })
}

function bindAgentContainerRuntime(
  api: Cloudflare.Worker,
  containerApplication: AgentContainerApplications[keyof AgentContainerApplications],
  namespaceOptions: { logicalId: string; className: string },
) {
  return Cloudflare.ContainerPlatform.bind(containerApplication).pipe(
    Effect.provideService(Self(Cloudflare.WorkerTypeId), api),
    Effect.provideService(
      Cloudflare.DurableObjectScope,
      createAgentContainerNamespace(api, namespaceOptions),
    ),
  )
}

function createAgentContainerNamespace(
  api: Cloudflare.Worker,
  options: { logicalId: string; className: string },
) {
  // oxlint-disable-next-line effect/avoid-any -- Alchemy resource type-bridge: hand-builds the DurableObject resource shape that ContainerPlatform.bind expects; Alchemy resource types are not Schema-decodable here.
  return {
    Type: "Cloudflare.DurableObject",
    LogicalId: options.logicalId,
    kind: "Cloudflare.DurableObject",
    name: options.className,
    namespaceId: api.durableObjectNamespaces.pipe(
      Output.map((namespaces) => namespaces[options.className]),
    ),
  } as unknown as Cloudflare.DurableObject
}

// oxlint-disable-next-line effect/avoid-any -- Type-only export placeholder: ApiWorker exists solely to surface the createApi resource type for binding declarations; it is never read at runtime.
export const ApiWorker = null as unknown as ReturnType<typeof createApi>
export type ApiWorkerResource = ReturnType<typeof createApi>
